### ISSUE TITLE
Expected 4-dimensional input for 4-dimensional weight 64 1 3 3

### ISSUE THREAD

**Issue by shariq-ali** [ugent-korea/pytorch-unet-segmentation#11]
Hello i'm new on pytorch. your example is very good. It works on your dataset but when i use it for my dataset it gives my error 

Traceback (most recent call last):
  File "main.py", line 58, in <module>
    train_model(model, SEM_train_load, criterion, optimizer)
  File "/content/gdrive/My Drive/Colab Notebooks/pytorch-unet-segmentation-master/src/modules.py", line 26, in train_model
    outputs = model(images)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/Colab Notebooks/pytorch-unet-segmentation-master/src/advanced_model.py", line 105, in forward
    x, conv1 = self.Conv_down1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/Colab Notebooks/pytorch-unet-segmentation-master/src/advanced_model.py", line 48, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/Colab Notebooks/pytorch-unet-segmentation-master/src/advanced_model.py", line 29, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 1 3 3, but got 5-dimensional input of size [2, 1, 572, 572, 187] instead

**Comment by shariq-ali** [comment]
I have RGB images as input and mask. i tried to change the in_channel to 3 but it gives me this error.  attached are the input image and mask.
![wheat2017_0002](https://user-images.githubusercontent.com/50959512/72000036-41c88480-3264-11ea-86ee-cdfc5c4b44b9.jpg)
![wheat2017_0002](https://user-images.githubusercontent.com/50959512/72000042-43924800-3264-11ea-877c-865eea534232.png)

**Comment by PyeongKim** [comment]
The masks should not be RGB. It should be single channel images.
